### ISSUE TITLE
post_convert行为奇怪

### ISSUE THREAD

**Issue by tzngit** [bttscut/xls-converter#1]
post_convert有时候会调用多次，有点奇怪

**Comment by bttscut** [comment]
```
export = {
    {"物品测试.xls", "Sheet1", "example.lua", "item_test", {}},
    {"物品测试2.xls", "防具定义", "example.lua", "item_test", {}},
}
```

这种情况下会调用多次，已经修改，同个导出名字-同个导表脚本的配置，脚本中的post_convert方法只会被调用一次，如果同个导出名字-不同导表脚本都配置了post_convert方法，则报错，应该不会出现这种需求。<br>
commit a99f27b47a14daf564942ef370856b8d8d9ceef9
